version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/action/teamdev
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    # - location: scripts/deploy.sh
    - location: scripts/debug.sh
      timeout: 60
      runas: ec2-user
